package burp;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SettingsTab implements ITab {
    private JComboBox comboBoxFingerprint;
    private JPanel panelMain;
    private JLabel labelFingerprint;
    private JTextField textFieldEmulateProxyAddress;
    private JTextField textFieldInterceptProxyAddress;
    private JTextField textFieldBurpProxyAddress;
    private JLabel labelEmulateProxyAddress;
    private JButton buttonSave;
    private JLabel labelTimeout;
    private JSpinner spinnerHttpTimout;
    private JSpinner spinnerKeepAlive;
    private JLabel labelKeepAlive;
    private JLabel labelIdleConnTimeout;
    private JSpinner spinnerIdleConnTimeout;
    private JLabel labelTlsHandshakeTimeout;
    private JSpinner spinnerTlsHandshakeTimeout;
    private JLabel labelHexClientHello;
    private JTextField textFieldHexClientHello;
    private JLabel labelInterceptProxyAddress;
    private JLabel labelBurpProxyAddress;
    private JRadioButton radioButtonUseInterceptedFingerprint;

    @Override
    public String getTabCaption() {
        return "Awesome TLS";
    }

    @Override
    public Component getUiComponent() {
        return panelMain;
    }

    public SettingsTab(Settings settings) {
        textFieldInterceptProxyAddress.setText(settings.getInterceptProxyAddress());
        textFieldBurpProxyAddress.setText(settings.getBurpProxyAddress());
        textFieldEmulateProxyAddress.setText(settings.getEmulateProxyAddress());
        textFieldHexClientHello.setText(settings.getHexClientHello());

        spinnerHttpTimout.setValue(settings.getHttpTimeout());
        spinnerKeepAlive.setValue(settings.getHttpKeepAliveInterval());
        spinnerIdleConnTimeout.setValue(settings.getIdleConnTimeout());
        spinnerTlsHandshakeTimeout.setValue(settings.getTlsHandshakeTimeout());

        for (var item : settings.getFingerprints()) {
            comboBoxFingerprint.addItem(item);
        }
        comboBoxFingerprint.setSelectedItem(settings.getFingerprint());

        buttonSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                settings.setEmulateProxyAddress(textFieldEmulateProxyAddress.getText());
                settings.setInterceptProxyAddress(textFieldInterceptProxyAddress.getText());
                settings.setBurpProxyAddress(textFieldEmulateProxyAddress.getText());
                settings.setFingerprint((String) comboBoxFingerprint.getSelectedItem());
                settings.setHexClientHello(textFieldHexClientHello.getText());
                settings.setUseInterceptedFingerprint(radioButtonUseInterceptedFingerprint.isSelected());
                settings.setHttpTimeout((int) spinnerHttpTimout.getValue());
                settings.setIdleConnTimeout((int) spinnerIdleConnTimeout.getValue());
                settings.setHttpKeepAliveInterval((int) spinnerKeepAlive.getValue());
                settings.setTlsHandshakeTimeout((int) spinnerTlsHandshakeTimeout.getValue());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(22, 7, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        panelMain.add(spacer1, new GridConstraints(21, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        labelInterceptProxyAddress = new JLabel();
        labelInterceptProxyAddress.setRequestFocusEnabled(false);
        labelInterceptProxyAddress.setText("Intercept proxy address:");
        labelInterceptProxyAddress.setToolTipText("");
        panelMain.add(labelInterceptProxyAddress, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldInterceptProxyAddress = new JTextField();
        textFieldInterceptProxyAddress.setToolTipText("Local address the intercept proxy server should listen on. Use it to configure proxy on your client. Requires extension reload.");
        panelMain.add(textFieldInterceptProxyAddress, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelBurpProxyAddress = new JLabel();
        labelBurpProxyAddress.setRequestFocusEnabled(false);
        labelBurpProxyAddress.setText("Burp proxy address:");
        labelBurpProxyAddress.setToolTipText("");
        panelMain.add(labelBurpProxyAddress, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldBurpProxyAddress = new JTextField();
        panelMain.add(textFieldBurpProxyAddress, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelEmulateProxyAddress = new JLabel();
        labelEmulateProxyAddress.setRequestFocusEnabled(false);
        labelEmulateProxyAddress.setText("Emulate proxy address:");
        labelEmulateProxyAddress.setToolTipText("");
        panelMain.add(labelEmulateProxyAddress, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldEmulateProxyAddress = new JTextField();
        textFieldEmulateProxyAddress.setToolTipText("Local address the emulate proxy server should listen on. Requires extension reload.");
        panelMain.add(textFieldEmulateProxyAddress, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelFingerprint = new JLabel();
        labelFingerprint.setEnabled(true);
        labelFingerprint.setHorizontalAlignment(10);
        labelFingerprint.setText("Fingerprint:");
        labelFingerprint.setVerticalAlignment(0);
        labelFingerprint.setVerticalTextPosition(0);
        panelMain.add(labelFingerprint, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboBoxFingerprint = new JComboBox();
        panelMain.add(comboBoxFingerprint, new GridConstraints(7, 0, 2, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelHexClientHello = new JLabel();
        labelHexClientHello.setText("Hex Client Hello");
        panelMain.add(labelHexClientHello, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldHexClientHello = new JTextField();
        textFieldHexClientHello.setToolTipText("Custom client hello as hex stream.");
        panelMain.add(textFieldHexClientHello, new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        radioButtonUseInterceptedFingerprint = new JRadioButton();
        radioButtonUseInterceptedFingerprint.setText("Use intercepted tls fingerprint");
        panelMain.add(radioButtonUseInterceptedFingerprint, new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelTimeout = new JLabel();
        labelTimeout.setText("Http connection timeout (seconds)");
        panelMain.add(labelTimeout, new GridConstraints(12, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spinnerHttpTimout = new JSpinner();
        spinnerHttpTimout.setToolTipText("The maximum amount of time a dial will wait for a connect to complete.");
        panelMain.add(spinnerHttpTimout, new GridConstraints(13, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelKeepAlive = new JLabel();
        labelKeepAlive.setText("Http keep alive interval");
        panelMain.add(labelKeepAlive, new GridConstraints(14, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spinnerKeepAlive = new JSpinner();
        spinnerKeepAlive.setToolTipText("Specifies the interval between keep-alive probes for an active network connection.");
        panelMain.add(spinnerKeepAlive, new GridConstraints(15, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelIdleConnTimeout = new JLabel();
        labelIdleConnTimeout.setText("Idle connection timeout");
        panelMain.add(labelIdleConnTimeout, new GridConstraints(16, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spinnerIdleConnTimeout = new JSpinner();
        spinnerIdleConnTimeout.setToolTipText("The maximum amount of time an idle (keep-alive) connection will remain idle before closing itself.");
        panelMain.add(spinnerIdleConnTimeout, new GridConstraints(17, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelTlsHandshakeTimeout = new JLabel();
        labelTlsHandshakeTimeout.setText("TLS handshake timeout");
        panelMain.add(labelTlsHandshakeTimeout, new GridConstraints(18, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        spinnerTlsHandshakeTimeout = new JSpinner();
        spinnerTlsHandshakeTimeout.setToolTipText("The maximum amount of time to wait for a TLS handshake.");
        panelMain.add(spinnerTlsHandshakeTimeout, new GridConstraints(19, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonSave = new JButton();
        buttonSave.setText("Save all settings");
        panelMain.add(buttonSave, new GridConstraints(20, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
